version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"


    cd build-windows\

    nmake /f bake.mak
test_script:
- cmd: bake.exe setup