on: [ push, pull_request ]

jobs:
  build-linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc-7
            cxx: g++-7
          - cc: gcc-8
            cxx: g++-8
          - cc: gcc-9
            cxx: g++-9
          - cc: gcc-10
            cxx: g++-10
          - cc: clang-8
            cxx: clang++-8
          - cc: clang-9
            cxx: clang++-9
          - cc: clang-10
            cxx: clang++-10

    steps:
      - uses: actions/checkout@v2
      - name: install compiler
        run: |
          sudo apt-get install -y ${{ matrix.compiler.cc }}
          sudo apt-get install -y ${{ matrix.compiler.cxx }}

      - name: setup
        run: |
          ./setup.sh

      - name: build examples (debug)
        run: |
          bake examples --strict
